const projects=[{id:"WH-01",name:"Scoring automático",description:"Genera el reporte diario por broker, lo archiva en Drive y lo envía por mail. Ejecución automática de lunes a viernes a las 18 hs.",status:"activo",url:"https://drive.google.com/drive/folders/1tPFUEsRC2ZB-OmmN94o8RdsIokMniZ3b"},{id:"WH-02",name:"Mora automatizada",description:"Motor Python operativo: consulta Prevención y actualiza estados, cuotas e historial de cambios desde la PC del trabajo.",status:"activo",url:"mora.html"},{id:"WH-03",name:"Mini Hub — Prevención",description:"Consulta rápida de percentiles de menores por sexo y edad: altura y peso de referencia.",status:"activo",url:"https://rodrissj23.github.io/MINI-HUB---PREVENCION/"},{id:"WH-04",name:"Control de liquidaciones",description:"Cruza Altas vs. Ventas por cápitas y detecta diferencias en la liquidación mensual.",status:"activo",url:"https://rodrissj23.github.io/control-liquidaciones/"},{id:"WH-05",name:"Mi liquidación",description:"Dashboard de comisiones: ventas, comisión esperada vs. liquidada y diferencias.",status:"activo",url:"https://rodrissj23.github.io/DASHBOARD-COMISIONES/"}];
const futureItems=[{icon:"✉",name:"Gmail",desc:"Mails laborales filtrados por remitentes importantes."},{icon:"◌",name:"WhatsApp",desc:"Canal de trabajo y consultas."},{icon:"◉",name:"Voz",desc:"V1.4 activa: respuesta local + aviso sonoro."}];
const attentionItems=[{level:"medium",title:"Gmail laboral pendiente de conexión",detail:"Filtro listo: falta publicar la API desde la cuenta del trabajo.",tag:"PENDIENTE"},{level:"ok",title:"Mora automatizada operativa",detail:"Motor local disponible para control de estados y cuotas.",tag:"OK"},{level:"ok",title:"Scoring automático",detail:"Programado de lunes a viernes a las 18:00.",tag:"OK"}];
const statusLabel={activo:"ACTIVO",desarrollo:"EN DESARROLLO",planificado:"PLANIFICADO"};
const MINI_DATA={meses:{1:{v:[54,4],m:[53,4]},2:{v:[58,5],m:[56,5]},3:{v:[61,6],m:[59,5]},4:{v:[64,7],m:[61,6]},5:{v:[66,8],m:[63,6]},6:{v:[68,8],m:[65,7]},7:{v:[69,9],m:[67,8]},8:{v:[71,9],m:[69,8]},9:{v:[72,9],m:[70,8]},10:{v:[73,10],m:[72,9]},11:{v:[75,10],m:[73,9]}},anios:{1:{v:[76,11],m:[74,10]},2:{v:[88,13],m:[86,12]},3:{v:[96,15],m:[94,15]},4:{v:[104,17],m:[101,17]},5:{v:[110,19],m:[108,19]},6:{v:[116,21],m:[113,21]},7:{v:[122,23],m:[120,23]},8:{v:[128,26],m:[125,26]},9:{v:[132,29],m:[130,30]},10:{v:[137,32],m:[135,34]},11:{v:[142,36],m:[140,37]},12:{v:[148,39],m:[148,43]},13:{v:[153,44],m:[154,47]},14:{v:[160,51],m:[158,51]},15:{v:[166,57],m:[160,53]},16:{v:[170,61],m:[161,55]},17:{v:[172,64],m:[162,56]},18:{v:[173,66],m:[163,57]}}};
const attentionList=document.querySelector('#attention-list');attentionItems.forEach(a=>{const el=document.createElement('article');el.className=`attention-item ${a.level}`;el.innerHTML=`<span class="attention-dot"></span><div class="attention-copy"><strong>${a.title}</strong><span>${a.detail}</span></div><span class="attention-tag">${a.tag}</span>`;attentionList.appendChild(el)});
const grid=document.querySelector('#projects'),countEl=document.querySelector('#project-count');const activos=projects.filter(p=>p.status==='activo').length,desarrollo=projects.filter(p=>p.status==='desarrollo').length;countEl.textContent=`${projects.length} sistemas`;projects.forEach(p=>{const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="card-top"><span class="card-id">${p.id}</span><span class="status-tag ${p.status}">${statusLabel[p.status]}</span></div><h3>${p.name}</h3><p>${p.description}</p><button class="card-open" type="button">Abrir →</button>`;card.querySelector('.card-open').addEventListener('click',()=>window.open(p.url,'_blank','noopener,noreferrer'));grid.appendChild(card)});
const futureRow=document.querySelector('#future');futureItems.forEach(f=>{const item=document.createElement('div');item.className='future-item';item.innerHTML=`<strong>${f.icon} ${f.name}</strong><span>${f.desc}</span>`;futureRow.appendChild(item)});document.querySelector('#statusbar').innerHTML=`<span>proyectos activos: <b>${activos}</b></span><span>en desarrollo: <b>${desarrollo}</b></span><span>fase actual: <b>VOICE V1.4</b></span>`;
const dayFmt=new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'long',year:'numeric'});document.querySelector('#today').textContent=dayFmt.format(new Date());function updateGreeting(){const h=new Date().getHours();document.querySelector('#greeting').textContent=`${h<12?'Buen día':h<19?'Buenas tardes':'Buenas noches'}, Rodrigo.`}updateGreeting();function tickClock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('es-AR',{hour12:false})}tickClock();setInterval(tickClock,1000);
const commandInput=document.querySelector('#command-input'),commandRun=document.querySelector('#command-run'),commandFeedback=document.querySelector('#command-feedback'),voiceRun=document.querySelector('#voice-run'),voiceLabel=document.querySelector('#voice-label'),voiceDot=document.querySelector('#voice-dot');
const WORD_NUMBERS={uno:1,una:1,dos:2,tres:3,cuatro:4,cinco:5,seis:6,siete:7,ocho:8,nueve:9,diez:10,once:11,doce:12,trece:13,catorce:14,quince:15,dieciseis:16,diecisiete:17,dieciocho:18};
function normalizeCommand(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[.,;:!?¿¡]/g,' ').trim().replace(/\s+/g,' ')}
function spokenNumbersToDigits(v){let q=normalizeCommand(v);Object.entries(WORD_NUMBERS).forEach(([w,n])=>q=q.replace(new RegExp(`\\b${w}\\b`,'g'),String(n)));return q}
function normalizeVoiceCommand(v){let q=spokenNumbersToDigits(v);q=q.replace(/\beme\b/g,'m').replace(/\buve\b/g,'v').replace(/\bve corta\b/g,'v');q=q.replace(/^abrir\s+/,'').replace(/^abre\s+/,'').replace(/^abri\s+/,'').replace(/^quiero\s+(ver|abrir)\s+/,'');return q.trim()}
function extractMiniHubQuery(raw){const q=normalizeVoiceCommand(raw);let sex=null;if(/\b(mujer|nena|nina|femenino)\b/.test(q)||/(^|\s)m(?=\s|\d)/.test(q))sex='m';if(/\b(varon|hombre|nene|nino|masculino)\b/.test(q)||/(^|\s)v(?=\s|\d)/.test(q))sex='v';const unit=/\bmes(es)?\b/.test(q)?'meses':'anios';const ageMatch=q.match(/\b(\d{1,2})\b/);const age=ageMatch?Number(ageMatch[1]):null;if(!sex||age===null)return null;if(unit==='meses'&&(age<1||age>11))return null;if(unit==='anios'&&(age<1||age>18))return null;return{sex,age,unit}}
function isCompleteVoiceCommand(raw){const q=normalizeVoiceCommand(raw);if(extractMiniHubQuery(raw))return true;if(q.includes('mora'))return true;if(q.includes('scoring')||q.includes('reporte'))return true;if(q.includes('control')&&q.includes('liquid'))return true;if(q.includes('mi liquid')||q.includes('comision'))return true;return false}
function openTarget(url){window.open(url,'_blank','noopener,noreferrer')}
let preferredVoice=null;
function chooseVoice(){if(!('speechSynthesis' in window))return null;const voices=window.speechSynthesis.getVoices();const spanish=voices.filter(v=>/^es([-_]|$)/i.test(v.lang));preferredVoice=spanish.find(v=>/argentin|es-ar/i.test(`${v.name} ${v.lang}`))||spanish.find(v=>/google|microsoft|natural|neural/i.test(v.name))||spanish[0]||null;return preferredVoice}
if('speechSynthesis' in window){chooseVoice();window.speechSynthesis.onvoiceschanged=chooseVoice}
function speak(text){if(!('speechSynthesis' in window)||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=preferredVoice?.lang||'es-AR';if(preferredVoice)u.voice=preferredVoice;u.rate=1.04;u.pitch=.98;u.volume=1;window.speechSynthesis.speak(u)}
let audioCtx=null;
function listeningBeep(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.setValueAtTime(880,audioCtx.currentTime);gain.gain.setValueAtTime(.0001,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.11,audioCtx.currentTime+.008);gain.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.095);osc.connect(gain);gain.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+.1)}catch(e){}}
function feedback(text,error=false,spoken=text){commandFeedback.textContent=text;commandFeedback.classList.toggle('error',error);if(spoken)speak(spoken)}
function answerMiniHub(mini){const row=(mini.unit==='meses'?MINI_DATA.meses:MINI_DATA.anios)[mini.age];if(!row)return feedback('No tengo datos para esa edad.',true,'No tengo datos para esa edad.');const [altura,peso]=row[mini.sex];const sexo=mini.sex==='m'?'Mujer':'Varón';const edadTxt=mini.unit==='meses'?`${mini.age} ${mini.age===1?'mes':'meses'}`:`${mini.age} ${mini.age===1?'año':'años'}`;const screen=`${sexo} · ${edadTxt} → ${altura} cm · ${peso} kg`;const spoken=`${sexo}, ${edadTxt}. Altura, ${altura} centímetros. Peso, ${peso} kilos.`;feedback(screen,false,spoken)}
function runCommand(value=null,fromVoice=false){const raw=String(value!==null?value:commandInput.value).trim(),q=normalizeVoiceCommand(raw);if(value!==null)commandInput.value=raw;if(!q){feedback('Escribí o decí un comando.',true,'No escuché ningún comando.');return}const mini=extractMiniHubQuery(raw);if(mini){answerMiniHub(mini);return}if(q.includes('mora')){feedback('Abriendo Mora automatizada…',false,'Abriendo Mora.');openTarget('mora.html');return}if(q.includes('scoring')||q.includes('reporte')){feedback('Abriendo Scoring…',false,'Abriendo Scoring.');openTarget('https://drive.google.com/drive/folders/1tPFUEsRC2ZB-OmmN94o8RdsIokMniZ3b');return}if(q.includes('control')&&q.includes('liquid')){feedback('Abriendo Control de liquidaciones…',false,'Abriendo Control de liquidaciones.');openTarget('https://rodrissj23.github.io/control-liquidaciones/');return}if(q.includes('mi liquid')||q.includes('comision')){feedback('Abriendo Mi liquidación…',false,'Abriendo Mi liquidación.');openTarget('https://rodrissj23.github.io/DASHBOARD-COMISIONES/');return}feedback(`Escuché “${raw}”, pero todavía no lo pude interpretar.`,true,'No entendí el comando.');}
commandRun.addEventListener('click',()=>runCommand());commandInput.addEventListener('keydown',e=>{if(e.key==='Enter')runCommand()});
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null,isListening=false,micPermissionGranted=false,finalTranscript='',interimTranscript='',finishTimer=null,manualStop=false,beeped=false;
function setVoiceState(state,label){voiceRun.classList.toggle('listening',state==='listening');voiceDot.classList.toggle('listening',state==='listening');voiceLabel.textContent=label;isListening=state==='listening'}
async function ensureMicPermission(){if(micPermissionGranted)return true;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error('Este navegador no permite solicitar acceso al micrófono.');setVoiceState('ready','Solicitando permiso de micrófono…');const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(track=>track.stop());micPermissionGranted=true;return true}
function clearFinishTimer(){if(finishTimer){clearTimeout(finishTimer);finishTimer=null}}
function fullTranscript(){return `${finalTranscript} ${interimTranscript}`.replace(/\s+/g,' ').trim()}
function finishVoice(){const heard=fullTranscript();if(!heard)return;clearFinishTimer();manualStop=true;try{recognition.stop()}catch(e){}commandInput.value=heard;setVoiceState('ready',`Escuché: “${heard}”`);runCommand(heard,true)}
function scheduleFinish(delay=300){clearFinishTimer();finishTimer=setTimeout(finishVoice,delay)}
async function startVoice(){if(!SpeechRecognition){feedback('El reconocimiento de voz no está disponible en este navegador.',true,'El reconocimiento de voz no está disponible en este navegador.');return}if(isListening){finishVoice();return}try{await ensureMicPermission();finalTranscript='';interimTranscript='';manualStop=false;beeped=false;clearFinishTimer();setVoiceState('ready','Iniciando escucha…');recognition.start()}catch(err){setVoiceState('ready','Voz lista');let msg='No pude activar el micrófono.';if(err&&['NotAllowedError','PermissionDeniedError'].includes(err.name))msg='Chrome no tiene permiso para usar el micrófono.';else if(err&&err.name==='NotFoundError')msg='No encontré ningún micrófono disponible.';feedback(msg,true,msg)}}
if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang='es-AR';recognition.interimResults=true;recognition.continuous=true;recognition.maxAlternatives=3;recognition.onstart=()=>setVoiceState('listening','Preparando micrófono…');recognition.onaudiostart=()=>{if(!beeped){beeped=true;listeningBeep()}setVoiceState('listening','Pip · hablá ahora')};recognition.onspeechstart=()=>setVoiceState('listening','Te estoy escuchando…');recognition.onresult=e=>{let newFinal='';let newInterim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript.trim();if(e.results[i].isFinal)newFinal+=` ${text}`;else newInterim+=` ${text}`}if(newFinal)finalTranscript=`${finalTranscript} ${newFinal}`.replace(/\s+/g,' ').trim();interimTranscript=newInterim.trim();const heard=fullTranscript();if(heard){commandInput.value=heard;setVoiceState('listening',`Escuchando: “${heard}”`);scheduleFinish(isCompleteVoiceCommand(heard)?90:280)}};recognition.onspeechend=()=>scheduleFinish(isCompleteVoiceCommand(fullTranscript())?80:220);recognition.onerror=e=>{clearFinishTimer();setVoiceState('ready','Voz lista');if(e.error==='aborted'&&manualStop)return;let msg='No pude entenderte. Probá otra vez.';if(e.error==='no-speech')msg='No escuché voz. Apretá Hablar y decí la frase completa.';else if(e.error==='audio-capture')msg='Chrome no pudo acceder al micrófono.';else if(e.error==='network')msg='El reconocimiento de voz tuvo un problema de red.';feedback(msg,true,msg)};recognition.onend=()=>{clearFinishTimer();if(!manualStop&&fullTranscript()){const heard=fullTranscript();commandInput.value=heard;runCommand(heard,true)}setVoiceState('ready','Voz lista');manualStop=false};voiceRun.addEventListener('click',startVoice)}else{voiceRun.addEventListener('click',()=>feedback('El reconocimiento de voz no está disponible en este navegador.',true,'Abrí Work Agent en Chrome para usar voz.'));voiceLabel.textContent='Voz no disponible en este navegador';}