const projects=[{id:"WH-01",name:"Scoring automático",description:"Genera el reporte diario por broker, lo archiva en Drive y lo envía por mail. Ejecución automática de lunes a viernes a las 18 hs.",status:"activo",url:"https://drive.google.com/drive/folders/1tPFUEsRC2ZB-OmmN94o8RdsIokMniZ3b"},{id:"WH-02",name:"Mora automatizada",description:"Motor Python operativo: consulta Prevención y actualiza estados, cuotas e historial de cambios desde la PC del trabajo.",status:"activo",url:"mora.html"},{id:"WH-03",name:"Mini Hub — Prevención",description:"Consulta rápida de percentiles de menores por sexo y edad: altura y peso de referencia.",status:"activo",url:"https://rodrissj23.github.io/MINI-HUB---PREVENCION/"},{id:"WH-04",name:"Control de liquidaciones",description:"Cruza Altas vs. Ventas por cápitas y detecta diferencias en la liquidación mensual.",status:"activo",url:"https://rodrissj23.github.io/control-liquidaciones/"},{id:"WH-05",name:"Mi liquidación",description:"Dashboard de comisiones: ventas, comisión esperada vs. liquidada y diferencias.",status:"activo",url:"https://rodrissj23.github.io/DASHBOARD-COMISIONES/"}];
const futureItems=[{icon:"✉",name:"Gmail",desc:"Mails laborales filtrados por remitentes importantes."},{icon:"◌",name:"WhatsApp",desc:"Canal de trabajo y consultas."},{icon:"◉",name:"Voz",desc:"V1 activa: reconocimiento y respuestas habladas en Chrome."}];
const attentionItems=[{level:"medium",title:"Gmail laboral pendiente de conexión",detail:"Filtro listo: falta publicar la API desde la cuenta del trabajo.",tag:"PENDIENTE"},{level:"ok",title:"Mora automatizada operativa",detail:"Motor local disponible para control de estados y cuotas.",tag:"OK"},{level:"ok",title:"Scoring automático",detail:"Programado de lunes a viernes a las 18:00.",tag:"OK"}];
const statusLabel={activo:"ACTIVO",desarrollo:"EN DESARROLLO",planificado:"PLANIFICADO"};
const attentionList=document.querySelector('#attention-list');attentionItems.forEach(a=>{const el=document.createElement('article');el.className=`attention-item ${a.level}`;el.innerHTML=`<span class="attention-dot"></span><div class="attention-copy"><strong>${a.title}</strong><span>${a.detail}</span></div><span class="attention-tag">${a.tag}</span>`;attentionList.appendChild(el)});
const grid=document.querySelector("#projects"),countEl=document.querySelector("#project-count");const activos=projects.filter(p=>p.status==="activo").length,desarrollo=projects.filter(p=>p.status==="desarrollo").length;countEl.textContent=`${projects.length} sistemas`;
projects.forEach(p=>{const card=document.createElement("article");card.className="card";card.innerHTML=`<div class="card-top"><span class="card-id">${p.id}</span><span class="status-tag ${p.status}">${statusLabel[p.status]}</span></div><h3>${p.name}</h3><p>${p.description}</p><button class="card-open" type="button">Abrir →</button>`;card.querySelector(".card-open").addEventListener("click",()=>window.open(p.url,"_blank","noopener,noreferrer"));grid.appendChild(card)});
const futureRow=document.querySelector("#future");futureItems.forEach(f=>{const item=document.createElement("div");item.className="future-item";item.innerHTML=`<strong>${f.icon} ${f.name}</strong><span>${f.desc}</span>`;futureRow.appendChild(item)});
document.querySelector("#statusbar").innerHTML=`<span>proyectos activos: <b>${activos}</b></span><span>en desarrollo: <b>${desarrollo}</b></span><span>fase actual: <b>VOICE V1</b></span>`;
const dayFmt=new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"long",year:"numeric"});document.querySelector("#today").textContent=dayFmt.format(new Date());function updateGreeting(){const h=new Date().getHours();document.querySelector("#greeting").textContent=`${h<12?"Buen día":h<19?"Buenas tardes":"Buenas noches"}, Rodrigo.`}updateGreeting();function tickClock(){document.querySelector("#clock").textContent=new Date().toLocaleTimeString("es-AR",{hour12:false})}tickClock();setInterval(tickClock,1000);
const commandInput=document.querySelector('#command-input'),commandRun=document.querySelector('#command-run'),commandFeedback=document.querySelector('#command-feedback'),voiceRun=document.querySelector('#voice-run'),voiceLabel=document.querySelector('#voice-label'),voiceDot=document.querySelector('#voice-dot');
const WORD_NUMBERS={uno:1,una:1,dos:2,tres:3,cuatro:4,cinco:5,seis:6,siete:7,ocho:8,nueve:9,diez:10,once:11,doce:12,trece:13,catorce:14,quince:15,dieciseis:16,diecisiete:17,dieciocho:18};
function normalizeCommand(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[.,;:!?¿¡]/g,' ').trim().replace(/\s+/g,' ')}
function spokenNumbersToDigits(v){let q=normalizeCommand(v);Object.entries(WORD_NUMBERS).forEach(([w,n])=>{q=q.replace(new RegExp(`\\b${w}\\b`,'g'),String(n))});return q}
function normalizeVoiceCommand(v){let q=spokenNumbersToDigits(v);q=q.replace(/\beme\b/g,'m').replace(/\buve\b/g,'v').replace(/\bve corta\b/g,'v').replace(/\bvaron\b/g,'varon').replace(/\banios?\b/g,'años').replace(/\bmeses?\b/g,'meses');q=q.replace(/^abrir\s+/,'').replace(/^abre\s+/,'').replace(/^abri\s+/,'').replace(/^quiero\s+(ver|abrir)\s+/,'');return q.trim()}
function extractMiniHubQuery(raw){const q=normalizeVoiceCommand(raw);let sex=null;if(/\b(mujer|nena|nina|femenino)\b/.test(q)||/^m\b/.test(q)||/^m\d/.test(q))sex='m';if(/\b(varon|hombre|nene|nino|masculino)\b/.test(q)||/^v\b/.test(q)||/^v\d/.test(q))sex='v';let unit=/\bmeses\b/.test(q)||/\bmes\b/.test(q)?'meses':'anios';let ageMatch=q.match(/\b(\d{1,2})\b/);if(!ageMatch){const code=q.match(/^[mv]\s*(\d{1,2})(m)?$/);if(code)ageMatch=[code[0],code[1]]}const age=ageMatch?Number(ageMatch[1]):null;if(!sex||age===null)return null;if(unit==='meses'&&(age<1||age>11))return null;if(unit==='anios'&&(age<1||age>18))return null;return{sex,age,unit,query:`${sex}${age}${unit==='meses'?'m':''}`}}
function commandScore(raw){const q=normalizeVoiceCommand(raw);let s=0;if(extractMiniHubQuery(raw))s+=100;if(q.includes('mora'))s+=80;if(q.includes('scoring')||q.includes('reporte'))s+=70;if(q.includes('control')&&q.includes('liquid'))s+=70;if(q.includes('mi liquid')||q.includes('comision'))s+=70;return s}
function bestAlternative(result){const options=[];for(let i=0;i<result.length;i++){const t=result[i].transcript.trim();options.push({text:t,score:commandScore(t),confidence:result[i].confidence||0})}options.sort((a,b)=>b.score-a.score||b.confidence-a.confidence);return options[0]?.text||result[0].transcript.trim()}
function openTarget(url){window.open(url,'_blank','noopener,noreferrer')}
function speak(text){if(!('speechSynthesis' in window)||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-AR';u.rate=1.02;u.pitch=1;window.speechSynthesis.speak(u)}
function feedback(text,error=false,spoken=text){commandFeedback.textContent=text;commandFeedback.classList.toggle('error',error);if(spoken)speak(spoken)}
function runCommand(value=null,fromVoice=false){const raw=String(value!==null?value:commandInput.value).trim(),q=normalizeVoiceCommand(raw);if(value!==null)commandInput.value=raw;if(!q){feedback('Escribí o decí un comando.',true,'No escuché ningún comando.');return}
  const mini=extractMiniHubQuery(raw);if(mini){const label=`${mini.sex==='m'?'Mujer':'Varón'} · ${mini.age} ${mini.unit==='meses'?(mini.age===1?'mes':'meses'):(mini.age===1?'año':'años')}`;feedback(`Consultando Mini Hub: ${label}…`,false,`Consultando ${label}.`);setTimeout(()=>openTarget(`https://rodrissj23.github.io/MINI-HUB---PREVENCION/?q=${encodeURIComponent(mini.query)}`),fromVoice?700:0);return}
  if(q.includes('mora')){feedback('Abriendo Mora automatizada…',false,'Abriendo Mora automatizada.');setTimeout(()=>openTarget('mora.html'),fromVoice?650:0);return}
  if(q.includes('scoring')||q.includes('reporte')){feedback('Abriendo Scoring…',false,'Abriendo Scoring.');setTimeout(()=>openTarget('https://drive.google.com/drive/folders/1tPFUEsRC2ZB-OmmN94o8RdsIokMniZ3b'),fromVoice?650:0);return}
  if(q.includes('control')&&q.includes('liquid')){feedback('Abriendo Control de liquidaciones…',false,'Abriendo Control de liquidaciones.');setTimeout(()=>openTarget('https://rodrissj23.github.io/control-liquidaciones/'),fromVoice?650:0);return}
  if(q.includes('mi liquid')||q.includes('comision')){feedback('Abriendo Mi liquidación…',false,'Abriendo Mi liquidación.');setTimeout(()=>openTarget('https://rodrissj23.github.io/DASHBOARD-COMISIONES/'),fromVoice?650:0);return}
  if(q==='liquidaciones'||q==='liquidacion'){feedback('¿Control o Mi liquidación? Probá “control liquidaciones” o “mi liquidación”.',true,'Decime control de liquidaciones o mi liquidación.');return}
  feedback(`Escuché “${raw}”, pero todavía no lo pude interpretar.`,true,'No pude interpretar ese comando. Probá diciendo mujer nueve años, varón seis meses, Mora o Scoring.');
}
commandRun.addEventListener('click',()=>runCommand());commandInput.addEventListener('keydown',e=>{if(e.key==='Enter')runCommand()});
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null,isListening=false,micPermissionGranted=false;
function setVoiceState(state,label){voiceRun.classList.toggle('listening',state==='listening');voiceDot.classList.toggle('listening',state==='listening');voiceLabel.textContent=label;isListening=state==='listening'}
async function ensureMicPermission(){if(micPermissionGranted)return true;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error('Este navegador no permite solicitar acceso al micrófono.');setVoiceState('ready','Solicitando permiso de micrófono…');const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(track=>track.stop());micPermissionGranted=true;return true}
async function startVoice(){if(!SpeechRecognition){feedback('El reconocimiento de voz no está disponible en este navegador.',true,'El reconocimiento de voz no está disponible en este navegador.');return}if(isListening){recognition.stop();return}try{await ensureMicPermission();setVoiceState('ready','Iniciando escucha…');recognition.start()}catch(err){setVoiceState('ready','Voz lista');const name=err&&err.name?err.name:'';let msg='No pude activar el micrófono.';if(name==='NotAllowedError'||name==='PermissionDeniedError')msg='Chrome no tiene permiso para usar el micrófono. Habilitalo para este sitio y probá otra vez.';else if(name==='NotFoundError')msg='No encontré ningún micrófono disponible.';else if(err&&err.message)msg=err.message;feedback(msg,true,msg)}}
if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang='es-AR';recognition.interimResults=false;recognition.continuous=false;recognition.maxAlternatives=5;recognition.onstart=()=>setVoiceState('listening','Escuchando…');recognition.onaudiostart=()=>setVoiceState('listening','Micrófono activo · hablá ahora');recognition.onspeechstart=()=>setVoiceState('listening','Te estoy escuchando…');recognition.onresult=e=>{const heard=bestAlternative(e.results[0]);commandInput.value=heard;setVoiceState('ready',`Escuché: “${heard}”`);runCommand(heard,true)};recognition.onerror=e=>{setVoiceState('ready','Voz lista');let msg='No pude entenderte. Probá otra vez.';if(e.error==='not-allowed'||e.error==='service-not-allowed')msg='El micrófono o el servicio de voz está bloqueado en Chrome.';else if(e.error==='no-speech')msg='No escuché voz. Apretá Hablar y probá de nuevo.';else if(e.error==='audio-capture')msg='Chrome no pudo acceder al micrófono.';else if(e.error==='network')msg='El reconocimiento de voz tuvo un problema de red.';feedback(msg,true,msg)};recognition.onend=()=>setVoiceState('ready','Voz lista');voiceRun.addEventListener('click',startVoice)}else{voiceRun.addEventListener('click',()=>feedback('El reconocimiento de voz no está disponible en este navegador. Abrilo en Chrome.',true,'Abrí Work Agent en Chrome para usar voz.'));voiceLabel.textContent='Voz no disponible en este navegador';}